# Generated by Django 3.2.25 on 2024-05-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Grower',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Industry',
            },
        ),
        migrations.CreateModel(
            name='PendingChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.CharField(max_length=250)),
                ('changeType', models.CharField(max_length=250)),
                ('editId', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'PendingChanges',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productGroup', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'ProductGroup',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=1024)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='stakeholderGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholderGroup', models.CharField(max_length=1024)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='PendingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcKey', models.CharField(blank=True, default=None, max_length=255)),
                ('Name', models.CharField(max_length=250)),
                ('Headquarters', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, default=None, max_length=512)),
                ('Sales', models.CharField(blank=True, max_length=255)),
                ('Product', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(blank=True, max_length=250)),
                ('State', models.CharField(blank=True, max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('Website', models.CharField(blank=True, max_length=250)),
                ('Products', models.CharField(blank=True, max_length=250)),
                ('sasContact', models.CharField(blank=True, max_length=250)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('pubPriv', models.CharField(blank=True, max_length=250)),
                ('Ticker', models.CharField(blank=True, max_length=250)),
                ('Naics', models.CharField(blank=True, max_length=250)),
                ('Phone', models.CharField(blank=True, max_length=250)),
                ('Email', models.CharField(blank=True, max_length=250)),
                ('Stakeholder', models.CharField(blank=True, max_length=250)),
                ('Principal', models.CharField(blank=True, max_length=250)),
                ('Founded', models.CharField(blank=True, max_length=250)),
                ('Employees', models.CharField(blank=True, max_length=250)),
                ('parentCompany', models.CharField(blank=True, max_length=250)),
                ('onMarket', models.CharField(blank=True, max_length=250)),
                ('productName', models.CharField(blank=True, max_length=250)),
                ('SKU', models.CharField(blank=True, max_length=250)),
                ('Notes', models.CharField(blank=True, max_length=250)),
                ('processingFocus', models.CharField(blank=True, max_length=1024)),
                ('facilitySize', models.CharField(blank=True, max_length=250)),
                ('biomassCap', models.CharField(blank=True, max_length=250)),
                ('extractionType', models.CharField(blank=True, max_length=1024)),
                ('GMP', models.CharField(blank=True, max_length=250)),
                ('news', models.CharField(blank=True, max_length=250)),
                ('reviews', models.CharField(blank=True, max_length=250)),
                ('Category', models.ManyToManyField(blank=True, to='helloworld.Category')),
                ('Grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.grower')),
                ('Industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.industry')),
                ('Solutions', models.ManyToManyField(blank=True, to='helloworld.Solution')),
                ('Stage', models.ManyToManyField(blank=True, to='helloworld.Stage')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.status')),
                ('productGroup', models.ManyToManyField(blank=True, to='helloworld.ProductGroup')),
                ('stakeholderGroup', models.ManyToManyField(blank=True, to='helloworld.stakeholderGroups')),
            ],
            options={
                'db_table': 'PendingCompanies',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcKey', models.CharField(blank=True, default=None, max_length=255)),
                ('Name', models.CharField(max_length=250)),
                ('Headquarters', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, default=None, max_length=512)),
                ('Sales', models.CharField(blank=True, max_length=255)),
                ('Product', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(blank=True, max_length=250)),
                ('State', models.CharField(blank=True, max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('Website', models.CharField(blank=True, max_length=250)),
                ('Products', models.CharField(blank=True, max_length=250)),
                ('sasContact', models.CharField(blank=True, max_length=250)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('pubPriv', models.CharField(blank=True, max_length=250)),
                ('Ticker', models.CharField(blank=True, max_length=250)),
                ('Naics', models.CharField(blank=True, max_length=250)),
                ('Phone', models.CharField(blank=True, max_length=250)),
                ('Email', models.CharField(blank=True, max_length=250)),
                ('Stakeholder', models.CharField(blank=True, max_length=250)),
                ('Principal', models.CharField(blank=True, max_length=250)),
                ('Founded', models.CharField(blank=True, max_length=250)),
                ('Employees', models.CharField(blank=True, max_length=250)),
                ('parentCompany', models.CharField(blank=True, max_length=250)),
                ('onMarket', models.CharField(blank=True, max_length=250)),
                ('productName', models.CharField(blank=True, max_length=250)),
                ('SKU', models.CharField(blank=True, max_length=250)),
                ('Notes', models.CharField(blank=True, max_length=250)),
                ('processingFocus', models.CharField(blank=True, max_length=1024)),
                ('facilitySize', models.CharField(blank=True, max_length=250)),
                ('biomassCap', models.CharField(blank=True, max_length=250)),
                ('extractionType', models.CharField(blank=True, max_length=1024)),
                ('GMP', models.CharField(blank=True, max_length=250)),
                ('news', models.CharField(blank=True, max_length=250)),
                ('reviews', models.CharField(blank=True, max_length=250)),
                ('Category', models.ManyToManyField(blank=True, to='helloworld.Category')),
                ('Grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.grower')),
                ('Industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.industry')),
                ('Solutions', models.ManyToManyField(blank=True, to='helloworld.Solution')),
                ('Stage', models.ManyToManyField(blank=True, to='helloworld.Stage')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloworld.status')),
                ('productGroup', models.ManyToManyField(blank=True, to='helloworld.ProductGroup')),
                ('stakeholderGroup', models.ManyToManyField(blank=True, to='helloworld.stakeholderGroups')),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
    ]
