# Generated by Django 3.2.23 on 2023-12-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Industry', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Headquarters', models.CharField(max_length=255)),
                ('Sales', models.CharField(max_length=255)),
                ('Product', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
    ]
