# Generated by Django 3.2.25 on 2024-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20240510_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='company',
            name='Notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='company',
            name='Products',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='SrcKey',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='Ticker',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='Website',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='company',
            name='pubPriv',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='Description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='Notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='SrcKey',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='Ticker',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='Website',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='pubPriv',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
