# Generated by Django 3.2.25 on 2024-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20240511_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'Resources',
            },
        ),
    ]
