# Generated by Django 3.2.25 on 2024-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
