# Generated by Django 3.2.25 on 2024-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_alter_resources_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
