# Generated by Django 3.2.25 on 2024-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_auto_20240521_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
