# Generated by Django 4.2.13 on 2024-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_alter_resources_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingID', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'UploadIndex',
            },
        ),
    ]
