# Generated by Django 4.2.13 on 2024-12-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0009_uploadindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='grower',
            options={'verbose_name': 'Grower', 'verbose_name_plural': 'Growers'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='pendingchanges',
            options={'verbose_name': 'Pending Change', 'verbose_name_plural': 'Pending Changes'},
        ),
        migrations.AlterModelOptions(
            name='pendingcompany',
            options={'verbose_name': 'Pending Company', 'verbose_name_plural': 'Pending Companies'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.AlterModelOptions(
            name='stakeholdergroups',
            options={'verbose_name': 'Stakeholder Group', 'verbose_name_plural': 'Stakeholder Groups'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='uploadindex',
            options={'verbose_name': 'Upload Index', 'verbose_name_plural': 'Upload Indexes'},
        ),
        migrations.AlterField(
            model_name='company',
            name='Grower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.grower'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.status'),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='Grower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.grower'),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='Industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.industry'),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.status'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='grower',
            table='grower',
        ),
        migrations.AlterModelTable(
            name='industry',
            table='industry',
        ),
        migrations.AlterModelTable(
            name='pendingchanges',
            table='pending_change',
        ),
        migrations.AlterModelTable(
            name='pendingcompany',
            table='pending_company',
        ),
        migrations.AlterModelTable(
            name='productgroup',
            table='product_group',
        ),
        migrations.AlterModelTable(
            name='resources',
            table='resource',
        ),
        migrations.AlterModelTable(
            name='solution',
            table='solution',
        ),
        migrations.AlterModelTable(
            name='stage',
            table='stage',
        ),
        migrations.AlterModelTable(
            name='stakeholdergroups',
            table='stakeholder_group',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
        migrations.AlterModelTable(
            name='uploadindex',
            table='upload_index',
        ),
    ]
