# Generated by Django 4.2.13 on 2025-02-13 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helloworld', '0011_company_latitude_company_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingchanges',
            name='companyId',
        ),
        migrations.RemoveField(
            model_name='pendingchanges',
            name='editId',
        ),
        migrations.AddField(
            model_name='company',
            name='pendingChanges',
            field=models.ManyToManyField(through='helloworld.PendingChanges', to='helloworld.pendingcompany'),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.company'),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pendingchanges',
            name='pending_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helloworld.pendingcompany'),
        ),
    ]
