# Generated by Django 4.2.13 on 2025-01-30 22:58

from django.db import migrations, models
from django.utils.timezone import make_aware, get_default_timezone
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0013_company_datecreated_company_lastupdated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dateCreated',
            field=models.DateTimeField(
                auto_now_add=True,
                default=make_aware(datetime(2024, 1, 1, 0, 0, 0), get_default_timezone())
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pendingcompany',
            name='dateCreated',
            field=models.DateTimeField(
                auto_now_add=True,
                default=make_aware(datetime(2024, 1, 1, 0, 0, 0), get_default_timezone())
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingcompany',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
