# Generated by Django 4.2.13 on 2025-03-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0012_remove_pendingchanges_companyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
