# Generated by Django 4.2.13 on 2025-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0013_company_datecreated_company_lastupdated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
