# Generated by Django 4.2.13 on 2025-04-13 04:16

#   Finding redundant fields in the Stages table, this field needs to be removed.
#   With this field being removed there are now duplicate keys.

#   ie. Products (2) and Products (3) are now just Products and Products.

#   All companies that relate to either Product should now point to one "Products"


from django.db import migrations


def fix_duplicate_stage_Products(apps, schema_editor):
    Company = apps.get_model('helloworld', 'Company')
    Stage = apps.get_model('helloworld', 'Stage')

    try:
        correct_stage = Stage.objects.get(id=5)
        duplicate_stage = Stage.objects.get(id=6)
    

        # Get all companies linked to the duplicate stage
        companies = Company.objects.filter(Stage=duplicate_stage)

        for company in companies:
            company.Stage.remove(duplicate_stage)
            company.Stage.add(correct_stage)
        
        duplicate_stage.delete()
        
    except Stage.DoesNotExist:
        pass

def fix_duplicate_stage_Markets(apps, schema_editor):
    Company = apps.get_model('helloworld', 'Company')
    Stage = apps.get_model('helloworld', 'Stage')

    try:
        correct_stage = Stage.objects.get(id=7)
        duplicate_stages=[  Stage.objects.get(id=8),  
                            Stage.objects.get(id=9),
                            Stage.objects.get(id=10)]
    

        # Get all companies linked to the duplicate stage
        
        for duplicate_stage in duplicate_stages:
            companies = Company.objects.filter(Stage=duplicate_stage)
            for company in companies:
                company.Stage.remove(duplicate_stage)
                company.Stage.add(correct_stage)
    
            duplicate_stage.delete()

    except Stage.DoesNotExist:
        pass
    
class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0014_company_datecreated_company_lastupdated_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_stage_Products),
        migrations.RunPython(fix_duplicate_stage_Markets),
        migrations.RemoveField(
            model_name='stage',
            name='category',
        ),
    ]
