# Generated by Django 4.2.13 on 2025-05-06 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0015_remove_stage_category_and_resolve_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
