# Generated by Django 4.2.13 on 2025-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0016_alter_company_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingchanges',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=250),
        ),
    ]
